# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        self.text = QtWidgets.QPushButton(Form)
        self.text.setGeometry(QtCore.QRect(350, 300, 300, 200))
        self.text.setObjectName("text")
        self.label = QtWidgets.QLabel(Form)
        self.text.setFont(QtGui.QFont("Times", 20, QtGui.QFont.Bold))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Главное окно"))
        self.text.setText(_translate("Form", "Начать"))
